[package]
name = "neenee-ai-sdk-openai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
neenee-core = { path = "../../platform/neenee-core" }
neenee-ai-sdk-core = { path = "../neenee-ai-sdk-core" }
async-trait = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
