//! Procedural macros for the neenee tool system.
//!
//! [`tool_schema`] (used as `#[derive(ToolSchema)]`) generates a
//! `parameters_schema() -> serde_json::Value` method on a struct that returns
//! the draft-07 JSON Schema the model sees for a tool's parameters — derived
//! from the struct's fields, so the schema and the parsed type can never drift
//! (the failure mode of hand-written `fn parameters()`).
//!
//! Supported field types: `String`, `bool`, `i32`/`i64`/`u32`/`u64`/`usize`
//! (→ integer), `f32`/`f64` (→ number), `Option<T>` (optional, unwraps T),
//! `Vec<T>` (array of T). Field attributes: `#[tool(desc = "...")]` sets the
//! description; fields without it get no description.
//!
//! This is deliberately a small, dependency-light macro (syn/quote only — no
//! `schemars` runtime) so the schema shape is fully visible and auditable in
//! generated code. Tools adopt it incrementally; hand-written schemas remain
//! valid.

use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, Type, parse_macro_input};

#[proc_macro_derive(ToolSchema, attributes(tool))]
pub fn tool_schema_derive(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;
    let fields = match &input.data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return syn::Error::new_spanned(
                    &input,
                    "ToolSchema only supports structs with named fields",
                )
                .to_compile_error()
                .into();
            }
        },
        _ => {
            return syn::Error::new_spanned(&input, "ToolSchema only supports structs")
                .to_compile_error()
                .into();
        }
    };

    // Build (field_name, json_type, description, is_required) per field.
    let mut field_entries = Vec::new();
    for f in fields {
        let ident = f.ident.as_ref().unwrap();
        let field_name = ident.to_string();
        let (json_type, optional) = rust_type_to_json(&f.ty);
        let desc = f.attrs.iter().find_map(|a| {
            if a.path().is_ident("tool") {
                a.parse_args::<syn::LitStr>().ok().map(|s| s.value())
            } else {
                None
            }
        });
        field_entries.push((field_name, json_type, desc, optional, ident));
    }

    // Generate the properties map and required array as token streams built
    // from serde_json::json! at runtime — simplest correct approach.
    let properties_builder = field_entries.iter().map(|(fname, jtype, desc, _, _)| {
        let fname = fname;
        match desc {
            Some(d) => quote! {
                props.insert(
                    #fname.to_string(),
                    serde_json::json!({"type": #jtype, "description": #d}),
                );
            },
            None => quote! {
                props.insert(
                    #fname.to_string(),
                    serde_json::json!({"type": #jtype}),
                );
            },
        }
    });
    let required_names: Vec<&String> = field_entries
        .iter()
        .filter(|(_, _, _, opt, _)| !opt)
        .map(|(n, _, _, _, _)| n)
        .collect();

    let expanded = quote! {
        impl #name {
            /// The draft-07 JSON Schema for this struct's fields, in the shape a
            /// tool advertises to the model (`{type:object, properties, required}`).
            /// Generated by `#[derive(ToolSchema)]` — never hand-written.
            pub fn parameters_schema() -> serde_json::Value {
                let mut props = serde_json::Map::new();
                #(#properties_builder)*
                serde_json::json!({
                    "type": "object",
                    "properties": props,
                    "required": [#(#required_names),*],
                    "additionalProperties": false,
                })
            }
        }
    };
    expanded.into()
}

/// Map a Rust type to its JSON-Schema type string, returning (type, optional).
fn rust_type_to_json(ty: &Type) -> (&'static str, bool) {
    let s = type_to_string(ty);
    // Option<T> → unwrap inner, mark optional.
    if let Some(inner) = strip_option(ty) {
        let (jt, _) = rust_type_to_json(inner);
        return (jt, true);
    }
    match s.as_str() {
        "String" | "&str" => ("string", false),
        "bool" => ("boolean", false),
        "i8" | "i16" | "i32" | "i64" | "isize" | "u8" | "u16" | "u32" | "u64" | "usize" => {
            ("integer", false)
        }
        "f32" | "f64" => ("number", false),
        _ => ("object", false), // fallback for nested structs / maps
    }
}

fn type_to_string(ty: &Type) -> String {
    quote::quote!(#ty).to_string().replace(' ', "")
}

/// If `ty` is `Option<T>`, return the inner `T`.
fn strip_option(ty: &Type) -> Option<&Type> {
    let path = match ty {
        Type::Path(p) => &p.path,
        _ => return None,
    };
    let last = path.segments.last()?;
    if last.ident != "Option" {
        return None;
    }
    let args = match &last.arguments {
        syn::PathArguments::AngleBracketed(a) => &a.args,
        _ => return None,
    };
    if let Some(syn::GenericArgument::Type(inner)) = args.first() {
        Some(inner)
    } else {
        None
    }
}
