// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningSupport } from "./ReasoningSupport";

/**
 * One user-declared model on a preset connection (ADR-0198): a hidden or
 * unstable upstream id the discovery intersection can never surface, pinned
 * to one connection. Lives in `muta-contracts` (not persistence) so the wire
 * request can carry it — persistence keys it per connection inside
 * `Connection::extra_models` and owns only storage, mirroring how
 * [`CapabilityOverrides`] rides [`crate::AgentRequest::EditProviderModel`].
 *
 * The id is exact (case-sensitive, consistent with
 * `muta_providers::registry::custom_baselines`); every capability field is
 * optional — a declared field overlays the registry default via the ADR-0149
 * resolution order (materialized as `RemoteModelMetadata` on the derived
 * channel), an absent field falls through to it.
 */
export type DeclaredModel = { 
/**
 * Exact model id sent on the wire and shown in the picker.
 */
id: string, 
/**
 * Context window in tokens, when the user knows it.
 */
context_window: number | null, 
/**
 * Maximum generated tokens, when known.
 */
max_output_tokens: number | null, 
/**
 * Reasoning representation, when known.
 */
thinking: ReasoningSupport | null, 
/**
 * Image-input support, when known.
 */
vision: boolean | null, 
/**
 * Native tool-call support, when known.
 */
tool_call: boolean | null, };
