//! The models.dev third-party catalog source (`RemoteCatalogSource::ModelsDev`).
//!
//! models.dev publishes a single central document
//! (`https://models.dev/api.json`) keyed by provider. This module owns both the
//! raw source — schema, fetch, in-memory single-flight cache, and the embedded
//! offline snapshot — and the mapping into the client's [`DiscoveredModel`]
//! discovery shape. It is an internal source adapter of the provider crate, not
//! a standalone crate: its only consumer is this registry (the `opencode-go`
//! and `openai` presets).
//!
//! ## Fetch strategy (ADR-0227)
//!
//! The fetched catalog lives in **process memory only** — there is no on-disk
//! cache, TTL, or background refresh. An explicit refresh ([`refresh`]) fetches
//! once under a single-flight lock and replaces the in-memory document; every
//! caller concurrently shares that one fetch. When the process starts cold and
//! a fetch fails, the committed, pruned [`snapshot.json`](snapshot.json)
//! embedded at build time is the offline floor. The per-connection reconciled
//! result is persisted by the caller (`muta-agent`'s `DiscoveryCache`), never
//! here.

mod schema;

use std::collections::BTreeMap;
use std::sync::{Arc, OnceLock};
use std::time::Duration;

use muta_contracts::ReasoningSupport;
use tokio::sync::{Mutex, RwLock};

use crate::DiscoveredModel;

pub use schema::{DevLimit, DevModalities, DevModel, DevProvider, DevReasoningOption};

/// The merged catalog: `provider_id -> provider entry`.
type Catalog = BTreeMap<String, DevProvider>;

/// The process-lifetime in-memory catalog. `None` until the first successful
/// fetch. Replaced wholesale by every explicit [`refresh`].
fn cell() -> &'static RwLock<Option<Arc<Catalog>>> {
    static CELL: OnceLock<RwLock<Option<Arc<Catalog>>>> = OnceLock::new();
    CELL.get_or_init(|| RwLock::new(None))
}

/// Single-flight guard: at most one upstream fetch runs at a time, and the
/// losers of the race read the winner's result from [`cell`].
fn fetch_lock() -> &'static Mutex<()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
}

/// Embedded snapshot of the models.dev catalog, pruned to the providers this
/// client consumes via `RemoteCatalogSource::ModelsDev`. Generated by
/// `scripts/refresh-models-dev-snapshot.sh` and committed; this serves as the
/// offline fallback on a cold start.
static SNAPSHOT_JSON: &str = include_str!("snapshot.json");

/// Hard timeout on a single fetch. Discovery runs on explicit user action; it
/// must never block the app on a slow/unreachable directory.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(10);

/// The upstream catalog endpoint.
const CATALOG_URL: &str = "https://models.dev/api.json";

const USER_AGENT: &str = concat!("muta/", env!("CARGO_PKG_VERSION"));

/// Errors produced by the models.dev client.
#[derive(Debug)]
pub enum ModelsDevError {
    /// The embedded snapshot is empty or unparseable (a build regression).
    Snapshot(String),
    /// The network fetch failed.
    Fetch(String),
    /// The response body was not valid JSON.
    Parse(String),
    /// The catalog fetched/embedded but contains no `provider_id`.
    MissingProvider(String),
    /// The provider exists but advertises no models.
    Empty,
}

impl std::fmt::Display for ModelsDevError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Snapshot(m) => write!(f, "models.dev snapshot unavailable: {m}"),
            Self::Fetch(m) => write!(f, "models.dev fetch failed: {m}"),
            Self::Parse(m) => write!(f, "models.dev response unparseable: {m}"),
            Self::MissingProvider(p) => write!(f, "models.dev has no provider entry: {p}"),
            Self::Empty => write!(f, "models.dev provider advertises no models"),
        }
    }
}

impl std::error::Error for ModelsDevError {}

/// Force a single upstream fetch and replace the in-memory catalog (ADR-0227).
///
/// This is the explicit refresh entry point. Concurrent and subsequent callers
/// share the single fetch; on failure the last good in-memory catalog is left
/// untouched and the error is returned, so a transient outage never shrinks the
/// served set.
pub async fn refresh() -> Result<(), ModelsDevError> {
    let _guard = fetch_lock().lock().await;
    let catalog = fetch().await?;
    store(catalog).await;
    Ok(())
}

/// Resolve a provider's model list, preferring the in-memory catalog. A cold
/// process fetches once (single-flight) and caches the result; if that fetch
/// fails, the embedded snapshot is the offline floor.
pub async fn provider_models(provider_id: &str) -> Result<Vec<DevModel>, ModelsDevError> {
    let catalog = match current_or_fetch().await {
        Ok(catalog) => catalog,
        Err(error) => {
            tracing::warn!(
                %error,
                provider = provider_id,
                "models.dev unavailable; using embedded snapshot"
            );
            Arc::new(parse_catalog(SNAPSHOT_JSON).map_err(ModelsDevError::Snapshot)?)
        }
    };
    provider_slice(&catalog, provider_id)
}

/// Resolve a `ModelsDev`-sourced provider's live model list and map it into
/// the client's discovery shape.
pub async fn models_dev_models(provider_id: &str) -> Result<Vec<DiscoveredModel>, ModelsDevError> {
    let models = provider_models(provider_id).await?;
    Ok(models.into_iter().map(from_dev_model).collect())
}

/// Refresh the shared models.dev catalog once (ADR-0227). Discovery calls this
/// before running its `ModelsDev` jobs so a single upstream fetch serves every
/// provider/connection in the pass. On failure the last good in-memory catalog
/// is retained.
pub async fn refresh_models_dev() -> Result<(), ModelsDevError> {
    refresh().await
}

/// Map one schema-neutral models.dev model into the client's discovered model.
///
/// Wire format is `None` here: models.dev's `npm` field describes the SDK
/// family, not an exact relay route, and the relay routes by the model's
/// registered protocol (see `route_for_model` / wire-override table), so the
/// discovery layer must not override it. Capability hints (family, context,
/// reasoning, effort, vision) are carried as `Option`s so the catalog folds
/// them into the remote-catalog overlay per preset (ADR-0203).
fn from_dev_model(m: DevModel) -> DiscoveredModel {
    let modalities_in = &m.modalities.input;
    let reasoning = Some(m.reasoning);
    let thinking = Some(if m.reasoning {
        // models.dev does not distinguish reasoning-content from summary; the
        // opencode-go relay surfaces it via the OpenAI-compatible stream, so
        // the conservative mapping is `ReasoningContent`.
        ReasoningSupport::ReasoningContent
    } else {
        ReasoningSupport::None
    });
    let effort_levels = m
        .reasoning_options
        .iter()
        .filter(|opt| opt.r#type == "effort")
        .flat_map(|opt| opt.values.iter().flatten())
        .cloned()
        .collect::<Vec<_>>();
    DiscoveredModel {
        id: m.id,
        picker_enabled: None,
        protocol: None,
        family: m.family.clone(),
        context_window: m.limit.context.map(|c| c as usize),
        max_output_tokens: m.limit.output.map(|o| o as u32),
        reasoning,
        thinking,
        tool_call: Some(m.tool_call),
        vision: if modalities_in.is_empty() {
            None
        } else {
            Some(modalities_in.iter().any(|m| m == "image"))
        },
        effort_levels: Some(effort_levels),
    }
}

/// The current in-memory catalog, fetching it under the single-flight lock when
/// the process has not populated it yet.
async fn current_or_fetch() -> Result<Arc<Catalog>, ModelsDevError> {
    if let Some(catalog) = current().await {
        return Ok(catalog);
    }
    let _guard = fetch_lock().lock().await;
    if let Some(catalog) = current().await {
        return Ok(catalog);
    }
    let catalog = fetch().await?;
    Ok(store(catalog).await)
}

async fn current() -> Option<Arc<Catalog>> {
    cell().read().await.clone()
}

async fn store(catalog: Catalog) -> Arc<Catalog> {
    let catalog = Arc::new(catalog);
    *cell().write().await = Some(Arc::clone(&catalog));
    catalog
}

/// Deserialize the top-level catalog: `{ provider_id: DevProvider }`.
fn parse_catalog(json: &str) -> Result<Catalog, String> {
    serde_json::from_str(json).map_err(|e| e.to_string())
}

/// Extract one provider's models from a merged catalog.
fn provider_slice(catalog: &Catalog, provider_id: &str) -> Result<Vec<DevModel>, ModelsDevError> {
    match catalog.get(provider_id) {
        Some(provider) if !provider.models.is_empty() => {
            Ok(provider.models.values().cloned().collect())
        }
        Some(_) => Err(ModelsDevError::Empty),
        None => Err(ModelsDevError::MissingProvider(provider_id.to_string())),
    }
}

/// Fetch `api.json` over the owned transport (ADR-0200): platform trust store,
/// redirects and content-encoding handled by the same code the model path uses.
async fn fetch() -> Result<Catalog, ModelsDevError> {
    let connector = netune::TlsConnector::platform(netune::TcpConnector::new())
        .map_err(|e| ModelsDevError::Fetch(e.to_string()))?;
    let client = netune::Client::new(
        connector,
        netune::Pool::default(),
        netune::ClientConfig {
            user_agent: USER_AGENT.to_string(),
            ..Default::default()
        },
    );
    let (target, path) =
        netune::Target::from_url(CATALOG_URL).map_err(|e| ModelsDevError::Fetch(e.to_string()))?;
    let head = netune::RequestHead::new(netune::Method::GET, path)
        .with_header("accept", "application/json");
    // One overall bound, request and body alike — the owned transport has no
    // client-wide timeout by design (a streaming turn must not be cut), so the
    // caller owns the deadline.
    let request = async {
        let mut response = client.request(&target, head, None).await?;
        if !response.head.status.is_success() {
            return Err(netune::NetError::Connect(format!(
                "HTTP {}",
                response.head.status
            )));
        }
        let body = response.body.read_to_end().await?;
        Ok::<_, netune::NetError>(String::from_utf8_lossy(&body).into_owned())
    };
    let body = tokio::time::timeout(REQUEST_TIMEOUT, request)
        .await
        .map_err(|_| ModelsDevError::Fetch("timed out".to_string()))?
        .map_err(|e| ModelsDevError::Fetch(e.to_string()))?;
    parse_catalog(&body).map_err(ModelsDevError::Parse)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snapshot() -> Catalog {
        parse_catalog(SNAPSHOT_JSON).expect("snapshot parses")
    }

    #[test]
    fn embedded_snapshot_is_parseable_and_contains_providers() {
        let catalog = snapshot();
        assert!(!catalog.is_empty(), "embedded snapshot must not be empty");
        // The snapshot is generated from the live catalog; it must at least
        // carry the provider the client consumes via this source.
        assert!(
            catalog.contains_key("opencode-go"),
            "embedded snapshot must contain the opencode-go provider"
        );
    }

    #[test]
    fn embedded_snapshot_is_pruned_to_consumed_providers() {
        // The snapshot must stay lean: it is pruned to the providers the
        // client actually consumes via `RemoteCatalogSource::ModelsDev`, so a
        // stray full-catalog embed (200+ providers) is caught here, not in
        // review.
        let catalog = snapshot();
        assert!(
            catalog.len() <= 16,
            "embedded snapshot is bloated: {} providers; prune it via \
             scripts/refresh-models-dev-snapshot.sh",
            catalog.len()
        );
        for id in ["opencode-go", "zai"] {
            assert!(
                catalog.contains_key(id),
                "embedded snapshot must contain the {id} provider"
            );
        }
        assert!(
            catalog.keys().all(|id| id == "opencode-go" || id == "zai"),
            "unexpected provider(s) in snapshot: {:?}",
            catalog.keys().collect::<Vec<_>>()
        );
    }

    #[test]
    fn slice_resolves_known_provider_and_rejects_unknown() {
        let catalog = snapshot();
        let models = provider_slice(&catalog, "opencode-go").expect("opencode-go exists");
        assert!(models.iter().any(|m| m.id == "deepseek-flash"));
        assert!(matches!(
            provider_slice(&catalog, "definitely-not-a-provider"),
            Err(ModelsDevError::MissingProvider(_))
        ));
    }

    fn sample_model() -> DevModel {
        DevModel {
            id: "glm-5.3".to_string(),
            name: "GLM-5.3".to_string(),
            family: Some("glm".to_string()),
            reasoning: true,
            reasoning_options: vec![DevReasoningOption {
                r#type: "effort".to_string(),
                values: vec![
                    Some("low".to_string()),
                    Some("high".to_string()),
                    Some("max".to_string()),
                ],
            }],
            tool_call: true,
            limit: DevLimit {
                context: Some(1_000_000),
                output: Some(131_072),
            },
            modalities: DevModalities {
                input: vec!["text".to_string()],
                output: vec!["text".to_string()],
            },
            attachment: false,
            status: None,
        }
    }

    #[test]
    fn maps_capabilities_and_effort_ladder() {
        let dm = from_dev_model(sample_model());
        assert_eq!(dm.id, "glm-5.3");
        assert_eq!(dm.family.as_deref(), Some("glm"));
        assert_eq!(dm.context_window, Some(1_000_000));
        assert_eq!(dm.max_output_tokens, Some(131_072));
        assert_eq!(dm.thinking, Some(ReasoningSupport::ReasoningContent));
        assert_eq!(dm.reasoning, Some(true));
        assert_eq!(dm.tool_call, Some(true));
        assert_eq!(dm.vision, Some(false));
        assert_eq!(
            dm.effort_levels,
            Some(vec![
                "low".to_string(),
                "high".to_string(),
                "max".to_string()
            ])
        );
        // Wire format is intentionally not asserted from models.dev.
        assert_eq!(dm.protocol, None);
    }

    #[test]
    fn vision_is_derived_from_input_modalities() {
        let mut m = sample_model();
        m.modalities.input = vec!["text".to_string(), "image".to_string()];
        assert_eq!(from_dev_model(m).vision, Some(true));
    }
}
