//! The models.dev third-party catalog source (`RemoteCatalogSource::ModelsDev`).
//!
//! models.dev publishes a single central document
//! (`https://models.dev/api.json`) keyed by provider. This module owns both the
//! raw source — schema, fetch, in-memory single-flight cache, and the embedded
//! offline snapshot — and the mapping into the client's [`DiscoveredModel`]
//! discovery shape. It is an internal source adapter of the provider crate, not
//! a standalone crate: its only consumer is this registry (the `opencode-go`
//! and `openai` presets).
//!
//! ## Fetch strategy (ADR-0227)
//!
//! The fetched catalog lives in **process memory only** — there is no on-disk
//! cache, TTL, or background refresh. An explicit refresh ([`refresh`]) fetches
//! once through a shared in-flight future and replaces the in-memory document; every
//! caller concurrently shares that one fetch. On a cold read, the committed,
//! pruned [`snapshot.json`](snapshot.json) embedded at build time is the offline
//! floor; reads never fetch. The per-connection reconciled
//! result is persisted by the caller (`muta-agent`'s `DiscoveryCache`), never
//! here.

mod schema;

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, OnceLock};

use futures::{
    FutureExt,
    future::{BoxFuture, Shared},
};
use muta_contracts::ReasoningSupport;
use tokio::sync::RwLock;

use crate::DiscoveredModel;

pub use schema::{DevLimit, DevModalities, DevModel, DevProvider, DevReasoningOption};

/// The merged catalog: `provider_id -> provider entry`.
type Catalog = BTreeMap<String, DevProvider>;

/// The process-lifetime in-memory catalog. `None` until the first successful
/// fetch. Replaced wholesale by every explicit [`refresh`].
fn cell() -> &'static RwLock<Option<Arc<Catalog>>> {
    static CELL: OnceLock<RwLock<Option<Arc<Catalog>>>> = OnceLock::new();
    CELL.get_or_init(|| RwLock::new(None))
}

/// A shared future retains the result for all overlapping callers, including
/// failures. A later explicit refresh replaces a completed flight. If a caller
/// is cancelled, another caller can continue polling the same bounded request.
type RefreshFuture = Shared<BoxFuture<'static, Result<(), ModelsDevError>>>;

#[derive(Default)]
struct RefreshFlight(Mutex<Option<RefreshFuture>>);

impl RefreshFlight {
    async fn run(
        &self,
        fetch: impl Future<Output = Result<(), ModelsDevError>> + Send + 'static,
    ) -> Result<(), ModelsDevError> {
        let flight = {
            let mut slot = self.0.lock().unwrap_or_else(|error| error.into_inner());
            match slot.as_ref().filter(|flight| flight.peek().is_none()) {
                Some(flight) => flight.clone(),
                None => {
                    let flight = fetch.boxed().shared();
                    *slot = Some(flight.clone());
                    flight
                }
            }
        };
        flight.await
    }
}

/// Embedded snapshot of the models.dev catalog, pruned to the providers this
/// client consumes via `RemoteCatalogSource::ModelsDev`. Generated by
/// `scripts/refresh-models-dev-snapshot.sh` and committed; this serves as the
/// offline fallback on a cold start.
static SNAPSHOT_JSON: &str = include_str!("snapshot.json");

/// The upstream catalog endpoint.
const CATALOG_URL: &str = "https://models.dev/api.json";

const USER_AGENT: &str = concat!("muta/", env!("CARGO_PKG_VERSION"));

/// Errors produced by the models.dev client.
#[derive(Debug, Clone)]
pub enum ModelsDevError {
    /// The embedded snapshot is empty or unparseable (a build regression).
    Snapshot(String),
    /// The network fetch failed.
    Fetch(String),
    /// The response body was not valid JSON.
    Parse(String),
    /// The catalog fetched/embedded but contains no `provider_id`.
    MissingProvider(String),
    /// The provider exists but advertises no models.
    Empty,
}

impl std::fmt::Display for ModelsDevError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Snapshot(m) => write!(f, "models.dev snapshot unavailable: {m}"),
            Self::Fetch(m) => write!(f, "models.dev fetch failed: {m}"),
            Self::Parse(m) => write!(f, "models.dev response unparseable: {m}"),
            Self::MissingProvider(p) => write!(f, "models.dev has no provider entry: {p}"),
            Self::Empty => write!(f, "models.dev provider advertises no models"),
        }
    }
}

impl std::error::Error for ModelsDevError {}

/// Force a single upstream fetch and replace the in-memory catalog (ADR-0227).
///
/// This is the explicit refresh entry point. Overlapping callers
/// share the single fetch; on failure the last good in-memory catalog is left
/// untouched and the error is returned, so a transient outage never shrinks the
/// served set.
pub async fn refresh() -> Result<(), ModelsDevError> {
    static FLIGHT: OnceLock<RefreshFlight> = OnceLock::new();
    FLIGHT
        .get_or_init(RefreshFlight::default)
        .run(async {
            let catalog = fetch().await?;
            store(catalog).await;
            Ok(())
        })
        .await
}

/// Read the latest in-memory catalog or the compiled offline floor. Reading
/// never starts network activity; only an explicit refresh fetches the source.
pub async fn provider_models(provider_id: &str) -> Result<Vec<DevModel>, ModelsDevError> {
    let catalog = match current().await {
        Some(catalog) => catalog,
        None => Arc::new(parse_catalog(SNAPSHOT_JSON).map_err(ModelsDevError::Snapshot)?),
    };
    provider_slice(&catalog, provider_id)
}

/// Resolve a `ModelsDev`-sourced provider's live model list and map it into
/// the client's discovery shape.
pub async fn models_dev_models(provider_id: &str) -> Result<Vec<DiscoveredModel>, ModelsDevError> {
    let models = provider_models(provider_id).await?;
    Ok(models.into_iter().map(from_dev_model).collect())
}

/// Refresh the shared models.dev catalog once (ADR-0227). Discovery calls this
/// before running its `ModelsDev` jobs so a single upstream fetch serves every
/// provider/connection in the pass. On failure the last good in-memory catalog
/// is retained.
pub async fn refresh_models_dev() -> Result<(), ModelsDevError> {
    refresh().await
}

/// Map one schema-neutral models.dev model into the client's discovered model.
///
/// Wire format is `None` here: models.dev's `npm` field describes the SDK
/// family, not an exact relay route, and the relay routes by the model's
/// registered protocol (see `route_for_model` / wire-override table), so the
/// discovery layer must not override it. Capability hints (family, context,
/// reasoning, effort, vision) are carried as `Option`s so the catalog folds
/// them into the remote-catalog overlay per preset (ADR-0203).
fn from_dev_model(m: DevModel) -> DiscoveredModel {
    let modalities_in = &m.modalities.input;
    let reasoning = Some(m.reasoning);
    let thinking = Some(if m.reasoning {
        // models.dev does not distinguish reasoning-content from summary; the
        // opencode-go relay surfaces it via the OpenAI-compatible stream, so
        // the conservative mapping is `ReasoningContent`.
        ReasoningSupport::ReasoningContent
    } else {
        ReasoningSupport::None
    });
    let effort_levels = m
        .reasoning_options
        .iter()
        .filter(|opt| opt.r#type == "effort")
        .flat_map(|opt| opt.values.iter().flatten())
        .cloned()
        .collect::<Vec<_>>();
    DiscoveredModel {
        id: m.id,
        picker_enabled: None,
        protocol: None,
        family: m.family.clone(),
        context_window: m.limit.context.map(|c| c as usize),
        max_output_tokens: m.limit.output.map(|o| o as u32),
        reasoning,
        thinking,
        tool_call: Some(m.tool_call),
        vision: if modalities_in.is_empty() {
            None
        } else {
            Some(modalities_in.iter().any(|m| m == "image"))
        },
        effort_levels: Some(effort_levels),
    }
}

async fn current() -> Option<Arc<Catalog>> {
    cell().read().await.clone()
}

async fn store(catalog: Catalog) -> Arc<Catalog> {
    let catalog = Arc::new(catalog);
    *cell().write().await = Some(Arc::clone(&catalog));
    catalog
}

/// Deserialize the top-level catalog: `{ provider_id: DevProvider }`.
fn parse_catalog(json: &str) -> Result<Catalog, String> {
    serde_json::from_str(json).map_err(|e| e.to_string())
}

/// Extract one provider's models from a merged catalog.
fn provider_slice(catalog: &Catalog, provider_id: &str) -> Result<Vec<DevModel>, ModelsDevError> {
    match catalog.get(provider_id) {
        Some(provider) if !provider.models.is_empty() => {
            Ok(provider.models.values().cloned().collect())
        }
        Some(_) => Err(ModelsDevError::Empty),
        None => Err(ModelsDevError::MissingProvider(provider_id.to_string())),
    }
}

/// Fetch `api.json` over the owned transport (ADR-0200): platform trust store,
/// redirects and content-encoding handled by the same code the model path uses.
async fn fetch() -> Result<Catalog, ModelsDevError> {
    let response = crate::http::Http::control_plane()
        .map_err(ModelsDevError::Fetch)?
        .get(
            CATALOG_URL,
            &[("accept", "application/json"), ("user-agent", USER_AGENT)],
        )
        .await
        .map_err(ModelsDevError::Fetch)?;
    if !response.is_success() {
        return Err(ModelsDevError::Fetch(format!("HTTP {}", response.status)));
    }
    let body = response.body;
    parse_catalog(&body).map_err(ModelsDevError::Parse)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn refresh_flight_shares_success_and_failure_then_allows_retry() {
        for fails in [false, true] {
            let flight = RefreshFlight::default();
            let gate = Arc::new(tokio::sync::Notify::new());
            let producer_gate = Arc::clone(&gate);
            let mut first = Box::pin(flight.run(async move {
                producer_gate.notified().await;
                if fails {
                    Err(ModelsDevError::Fetch("offline".into()))
                } else {
                    Ok(())
                }
            }));
            assert!(futures::poll!(&mut first).is_pending());
            let mut second = Box::pin(flight.run(async { panic!("duplicate fetch") }));
            assert!(futures::poll!(&mut second).is_pending());
            gate.notify_one();
            let (first, second) = tokio::join!(first, second);
            assert_eq!(first.is_err(), fails);
            assert_eq!(second.is_err(), fails);
            if fails {
                assert_eq!(
                    first.unwrap_err().to_string(),
                    second.unwrap_err().to_string()
                );
            }
            assert!(flight.run(async { Ok(()) }).await.is_ok());
        }
    }

    #[tokio::test]
    async fn refresh_flight_survives_caller_cancellation() {
        let flight = RefreshFlight::default();
        let gate = Arc::new(tokio::sync::Notify::new());
        let producer_gate = Arc::clone(&gate);
        let mut first = Box::pin(flight.run(async move {
            producer_gate.notified().await;
            Ok(())
        }));
        assert!(futures::poll!(&mut first).is_pending());
        drop(first);
        let mut second =
            Box::pin(flight.run(async { panic!("cancelled caller must not duplicate fetch") }));
        assert!(futures::poll!(&mut second).is_pending());
        gate.notify_one();
        assert!(second.await.is_ok());
    }

    fn snapshot() -> Catalog {
        parse_catalog(SNAPSHOT_JSON).expect("snapshot parses")
    }

    #[test]
    fn embedded_snapshot_is_parseable_and_contains_providers() {
        let catalog = snapshot();
        assert!(!catalog.is_empty(), "embedded snapshot must not be empty");
        // The snapshot is generated from the live catalog; it must at least
        // carry the provider the client consumes via this source.
        assert!(
            catalog.contains_key("opencode-go"),
            "embedded snapshot must contain the opencode-go provider"
        );
    }

    #[test]
    fn embedded_snapshot_is_pruned_to_consumed_providers() {
        // The snapshot must stay lean: it is pruned to the providers the
        // client actually consumes via `RemoteCatalogSource::ModelsDev`, so a
        // stray full-catalog embed (200+ providers) is caught here, not in
        // review.
        let catalog = snapshot();
        assert!(
            catalog.len() <= 16,
            "embedded snapshot is bloated: {} providers; prune it via \
             scripts/refresh-models-dev-snapshot.sh",
            catalog.len()
        );
        for id in ["opencode-go", "zai"] {
            assert!(
                catalog.contains_key(id),
                "embedded snapshot must contain the {id} provider"
            );
        }
        assert!(
            catalog.keys().all(|id| id == "opencode-go" || id == "zai"),
            "unexpected provider(s) in snapshot: {:?}",
            catalog.keys().collect::<Vec<_>>()
        );
    }

    #[test]
    fn slice_resolves_known_provider_and_rejects_unknown() {
        let catalog = snapshot();
        let models = provider_slice(&catalog, "opencode-go").expect("opencode-go exists");
        assert!(models.iter().any(|m| m.id == "deepseek-flash"));
        assert!(matches!(
            provider_slice(&catalog, "definitely-not-a-provider"),
            Err(ModelsDevError::MissingProvider(_))
        ));
    }

    fn sample_model() -> DevModel {
        DevModel {
            id: "glm-5.3".to_string(),
            name: "GLM-5.3".to_string(),
            family: Some("glm".to_string()),
            reasoning: true,
            reasoning_options: vec![DevReasoningOption {
                r#type: "effort".to_string(),
                values: vec![
                    Some("low".to_string()),
                    Some("high".to_string()),
                    Some("max".to_string()),
                ],
            }],
            tool_call: true,
            limit: DevLimit {
                context: Some(1_000_000),
                output: Some(131_072),
            },
            modalities: DevModalities {
                input: vec!["text".to_string()],
                output: vec!["text".to_string()],
            },
            attachment: false,
            status: None,
        }
    }

    #[test]
    fn maps_capabilities_and_effort_ladder() {
        let dm = from_dev_model(sample_model());
        assert_eq!(dm.id, "glm-5.3");
        assert_eq!(dm.family.as_deref(), Some("glm"));
        assert_eq!(dm.context_window, Some(1_000_000));
        assert_eq!(dm.max_output_tokens, Some(131_072));
        assert_eq!(dm.thinking, Some(ReasoningSupport::ReasoningContent));
        assert_eq!(dm.reasoning, Some(true));
        assert_eq!(dm.tool_call, Some(true));
        assert_eq!(dm.vision, Some(false));
        assert_eq!(
            dm.effort_levels,
            Some(vec![
                "low".to_string(),
                "high".to_string(),
                "max".to_string()
            ])
        );
        // Wire format is intentionally not asserted from models.dev.
        assert_eq!(dm.protocol, None);
    }

    #[test]
    fn vision_is_derived_from_input_modalities() {
        let mut m = sample_model();
        m.modalities.input = vec!["text".to_string(), "image".to_string()];
        assert_eq!(from_dev_model(m).vision, Some(true));
    }
}
