[package]
name = "neenee-quant"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
neenee-core = { path = "../neenee-core" }
neenee-agent = { path = "../neenee-agent" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
chrono = { workspace = true }

[dev-dependencies]
neenee-tools = { path = "../neenee-tools" }
tokio = { workspace = true }

[lints]
workspace = true
