//! `muta-models-dev` — a removable feature module that pulls the models.dev
//! central catalog (`https://models.dev/api.json`) into the client as a
//! **third-party** network source for a provider's model list.
//!
//! This is the `LiveCatalog::ModelsDev` source (see
//! `muta-providers::registry::LiveCatalog`): it feeds the same
//! `DiscoveredModel` reconciliation pipeline as first-party discovery, but
//! the *data* comes from the models.dev directory rather than the provider's
//! own endpoint. It is used when a provider's first-party `/models` is not the
//! authoritative served set or does not carry capability metadata (e.g.
//! `opencode-go`, whose relay publishes on models.dev).
//!
//! ## Removability
//!
//! The crate is deliberately standalone and returns **schema-neutral** types
//! ([`DevProvider`] / [`DevModel`]) rather than depending on
//! `muta-providers` — so it can be dropped without a dependency cycle, and a
//! build without it degrades to the compiled baselines.
//!
//! ## Fetch strategy (mirrors the opencode `ModelsDev` service)
//!
//! - Fetch `api.json` with a user agent + timeout.
//! - Cache to disk under the XDG cache dir with a freshness TTL.
//! - Guard concurrent writers with a cross-process file lock.
//! - Ship a committed, pruned snapshot (`snapshot.json`) for offline fallback,
//!   refreshed by `scripts/refresh-models-dev-snapshot.sh`.

#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

mod schema;

use muta_persistence::fsutil;
use muta_persistence::paths;
use std::collections::BTreeMap;
use std::path::PathBuf;
use std::time::Duration;

pub use schema::{DevLimit, DevModalities, DevModel, DevProvider, DevReasoningOption};

/// How often the background refresh loop re-fetches the models.dev catalog.
/// The disk cache also has its own freshness TTL, so an hour is plenty to keep
/// a long-running daemon's catalog within a couple of hours of upstream.
const REFRESH_PERIOD: Duration = Duration::from_secs(60 * 60);

/// A [`muta_contracts::DynamicCatalog`] that keeps the models.dev disk cache
/// fresh on a background cadence. Run it through the generic
/// [`muta_agent::dynamic::spawn_refresh`] wiring at startup; the first tick
/// fires immediately, then every [`Self::refresh_period`].
///
/// This only refreshes the *cache*. The per-connection reconciliation still
/// runs through model discovery, which reads the freshly refreshed cache on
/// its own schedule.
pub struct DynamicModelsDev;

impl muta_contracts::DynamicCatalog for DynamicModelsDev {
    fn id(&self) -> &'static str {
        "models-dev"
    }

    async fn refresh(&self) -> Result<(), String> {
        refresh().await.map_err(|e| e.to_string())
    }

    fn refresh_period(&self) -> Duration {
        REFRESH_PERIOD
    }
}

/// Embedded snapshot of the models.dev catalog, pruned to the providers this
/// client consumes via `LiveCatalog::ModelsDev` (currently `opencode-go`).
/// Generated by `scripts/refresh-models-dev-snapshot.sh` and committed; this
/// serves as the offline fallback when the network fetch fails or is disabled.
static SNAPSHOT_JSON: &str = include_str!("../snapshot.json");

/// How long a cached `api.json` is considered fresh before a background
/// refresh is warranted. Mirrors opencode's `ModelsDev` TTL.
const CACHE_TTL: Duration = Duration::from_secs(5 * 60);

/// Hard timeout on a single fetch. Discovery runs at startup; it must never
/// block the app on a slow/unreachable directory.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(10);

const USER_AGENT: &str = concat!("muta/", env!("CARGO_PKG_VERSION"));

/// Errors produced by the models.dev client.
#[derive(Debug)]
pub enum ModelsDevError {
    /// The embedded snapshot is empty or unparseable (a build regression).
    Snapshot(String),
    /// The network fetch failed.
    Fetch(String),
    /// The response body was not valid JSON.
    Parse(String),
    /// The catalog fetched/cached/embedded but contains no `provider_id`.
    MissingProvider(String),
    /// The provider exists but advertises no models.
    Empty,
    /// A persisted-cache read/write failure.
    Cache(String),
}

impl std::fmt::Display for ModelsDevError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Snapshot(m) => write!(f, "models.dev snapshot unavailable: {m}"),
            Self::Fetch(m) => write!(f, "models.dev fetch failed: {m}"),
            Self::Parse(m) => write!(f, "models.dev response unparseable: {m}"),
            Self::MissingProvider(p) => write!(f, "models.dev has no provider entry: {p}"),
            Self::Empty => write!(f, "models.dev provider advertises no models"),
            Self::Cache(m) => write!(f, "models.dev cache error: {m}"),
        }
    }
}

impl std::error::Error for ModelsDevError {}

/// The cache file for the models.dev catalog.
fn cache_path() -> PathBuf {
    paths::get().cache_dir.join("models-dev.json")
}

/// Resolve the models.dev catalog for a provider, trying (in order):
/// fresh disk cache → network fetch → embedded snapshot. The snapshot is
/// always present, so "provider not found" only surfaces if the embedded
/// snapshot truly lacks the provider.
pub async fn provider_models(provider_id: &str) -> Result<Vec<DevModel>, ModelsDevError> {
    // 1. Fresh disk cache (a plain read needs no lock).
    if let Some(provider) = read_cached_catalog().and_then(|c| c.get(provider_id).cloned()) {
        return Ok(provider.models.into_values().collect());
    }
    // 2. Network fetch + cache write. On any failure, fall through to the
    //    embedded snapshot.
    if let Ok(fetched) = fetch_and_cache().await
        && let Some(provider) = fetched.get(provider_id).cloned()
    {
        return Ok(provider.models.into_values().collect());
    }
    // 3. Embedded snapshot (offline fallback).
    let snapshot = parse_catalog(SNAPSHOT_JSON).map_err(ModelsDevError::Snapshot)?;
    match snapshot.get(provider_id) {
        Some(provider) if !provider.models.is_empty() => {
            Ok(provider.models.values().cloned().collect())
        }
        Some(_) => Err(ModelsDevError::Empty),
        None => Err(ModelsDevError::MissingProvider(provider_id.to_string())),
    }
}

/// Refresh the models.dev disk cache regardless of its age (the background
/// refresh loop calls this on its cadence, so a fresh catalog is available the
/// moment discovery next runs). Best-effort: a network failure leaves the last
/// good cache in place and reports the error for logging.
pub async fn refresh() -> Result<(), ModelsDevError> {
    fetch_and_cache().await.map(|_| ())
}

/// Deserialize the top-level catalog: `{ provider_id: DevProvider }`.
fn parse_catalog(json: &str) -> Result<BTreeMap<String, DevProvider>, String> {
    serde_json::from_str(json).map_err(|e| e.to_string())
}

/// Read a cached catalog from disk if it exists and is fresh.
fn read_cached_catalog() -> Option<BTreeMap<String, DevProvider>> {
    let path = cache_path();
    let (mtime, content) = {
        let Ok(meta) = std::fs::metadata(&path) else {
            return None;
        };
        let Ok(modified) = meta.modified() else {
            return None;
        };
        let Ok(content) = std::fs::read_to_string(&path) else {
            return None;
        };
        (modified, content)
    };
    if mtime.elapsed().map(|e| e <= CACHE_TTL).unwrap_or(false) {
        parse_catalog(&content).ok()
    } else {
        None
    }
}

/// Fetch `api.json` and write it to the cache under a cross-process lock.
async fn fetch_and_cache() -> Result<BTreeMap<String, DevProvider>, ModelsDevError> {
    let client = reqwest::Client::builder()
        .user_agent(USER_AGENT)
        .timeout(REQUEST_TIMEOUT)
        .build()
        .map_err(|e| ModelsDevError::Fetch(e.to_string()))?;
    let resp = client
        .get("https://models.dev/api.json")
        .send()
        .await
        .map_err(|e| ModelsDevError::Fetch(e.to_string()))?;
    if !resp.status().is_success() {
        return Err(ModelsDevError::Fetch(format!("HTTP {}", resp.status())));
    }
    let body = resp
        .text()
        .await
        .map_err(|e| ModelsDevError::Fetch(e.to_string()))?;
    let catalog = parse_catalog(&body).map_err(ModelsDevError::Parse)?;

    // Persist atomically under a cross-process lock so concurrent CLIs do not
    // corrupt the cache. A write failure is non-fatal (we still return the
    // freshly fetched catalog).
    let path = cache_path();
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let lock = tokio::task::spawn_blocking({
        let path = path.clone();
        move || fsutil::FileLock::acquire(&path)
    })
    .await
    .map_err(|e| ModelsDevError::Cache(e.to_string()))?
    .map_err(|e| ModelsDevError::Cache(e.to_string()))?;
    let write = fsutil::atomic_write_bytes(&path, body.as_bytes());
    drop(lock);
    if let Err(e) = write {
        tracing::warn!(error = %e, "could not write models.dev cache; using fetched catalog");
    }
    Ok(catalog)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_snapshot_is_parseable_and_contains_providers() {
        let catalog = parse_catalog(SNAPSHOT_JSON).expect("snapshot parses");
        assert!(!catalog.is_empty(), "embedded snapshot must not be empty");
        // The snapshot is generated from the live catalog; it must at least
        // carry the provider the client consumes via this source.
        assert!(
            catalog.contains_key("opencode-go"),
            "embedded snapshot must contain the opencode-go provider"
        );
    }

    #[test]
    fn embedded_snapshot_is_pruned_to_consumed_providers() {
        // The snapshot must stay lean: it is pruned to the providers the
        // client actually consumes via LiveCatalog::ModelsDev (as primary or
        // fallback), so a stray full-catalog embed (200+ providers) is caught
        // here, not in review.
        let catalog = parse_catalog(SNAPSHOT_JSON).expect("snapshot parses");
        assert!(
            catalog.len() <= 16,
            "embedded snapshot is bloated: {} providers; prune it via \
             scripts/refresh-models-dev-snapshot.sh",
            catalog.len()
        );
        // Every embedded provider must be one the client consumes via this
        // source — keep the script's PROVIDER_IDS and this set in sync.
        for id in ["opencode-go", "zai"] {
            assert!(
                catalog.contains_key(id),
                "embedded snapshot must contain the {id} provider (LiveCatalog::ModelsDev / fallback)"
            );
        }
        assert!(
            catalog.keys().all(|id| id == "opencode-go" || id == "zai"),
            "unexpected provider(s) in snapshot: {:?}",
            catalog.keys().collect::<Vec<_>>()
        );
    }

    #[test]
    fn missing_provider_reports_a_typed_error() {
        // The embedded snapshot is authoritative for the offline path, so an
        // unknown id must produce a typed MissingProvider error.
        let snapshot = parse_catalog(SNAPSHOT_JSON).expect("snapshot parses");
        assert!(
            !snapshot.contains_key("definitely-not-a-provider"),
            "test precondition: unknown id absent from snapshot"
        );
    }
}
