//! Build-time embedding of the web panel's static bundle.
//!
//! Source: `apps/web/dist` (override with `NEENEE_WEB_DIST`). When the dist
//! is absent — a bare `cargo build` without the pnpm toolchain — a
//! placeholder page is embedded instead so the daemon still compiles and
//! serves a helpful message at `/`.

// A build script panicking on an I/O failure is the correct failure mode;
// the workspace-wide `unwrap_used` denial targets shipping code.
#![allow(clippy::unwrap_used)]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = env::var_os("NEENEE_WEB_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join("../../apps/web/dist"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let staging = out_dir.join("web-assets");
    fs::create_dir_all(&staging).unwrap();

    println!("cargo:rerun-if-env-changed=NEENEE_WEB_DIST");
    println!("cargo:rerun-if-changed={}", dist.display());

    let real_dist = dist.is_dir() && dist.join("index.html").is_file();
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if real_dist {
        collect(&dist, &dist, &mut entries);
        entries.sort();
    } else {
        fs::write(
            staging.join("index.html"),
            PLACEHOLDER_HTML.replace("{}", &dist.display().to_string()),
        )
        .unwrap();
        entries.push(("index.html".to_string(), staging.join("index.html")));
    }

    // Copy every asset into the staging dir so generated code never references
    // paths outside OUT_DIR (keeps the crate hermetic for caching tools).
    let mut code = String::from(
        "// Generated by build.rs — do not edit.\n\
         /// (url path, content type, bytes)\n\
         pub static FILES: &[(&str, &str, &[u8])] = &[\n",
    );
    for (rel, abs) in &entries {
        let staged = staging.join(rel);
        if abs != &staged {
            fs::create_dir_all(staged.parent().unwrap()).unwrap();
            fs::copy(abs, &staged).unwrap();
        }
        println!("cargo:rerun-if-changed={}", abs.display());
        push_entry(&mut code, rel, content_type(rel), &staged);
    }
    code.push_str("];\n");
    code.push_str(&format!("pub static REAL_DIST: bool = {real_dist};\n"));
    fs::write(out_dir.join("assets.rs"), code).unwrap();
}

/// Append one generated entry using Rust's string-literal escaping.
///
/// In particular, Windows paths contain backslashes, which cannot be pasted
/// verbatim between quotes (`D:\\a` would otherwise contain the `\\a` escape).
/// Debug formatting a string produces a quoted, escaped Rust string literal
/// and also keeps unusual asset names from breaking the generated source.
fn push_entry(code: &mut String, rel: &str, mime: &str, staged: &Path) {
    let staged = staged.to_string_lossy();
    code.push_str(&format!(
        "    ({rel:?}, {mime:?}, include_bytes!({staged:?})),\n"
    ));
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}

fn content_type(path: &str) -> &'static str {
    match Path::new(path).extension().and_then(|e| e.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg" | "jpeg") => "image/jpeg",
        Some("webp") => "image/webp",
        Some("ico") => "image/x-icon",
        Some("json" | "map") => "application/json",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("ttf") => "font/ttf",
        _ => "application/octet-stream",
    }
}

const PLACEHOLDER_HTML: &str = r#"<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>neenee</title>
<style>body{font-family:ui-monospace,monospace;background:#0e1117;color:#e6edf3;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0}main{max-width:34em;line-height:1.6}code{background:#1f2533;padding:2px 6px;border-radius:4px}</style>
</head><body><main>
<h1>neenee web panel — not embedded</h1>
<p>This daemon was built without the web bundle. The daemon itself is running and its WebSocket control plane is live on this port.</p>
<p>To embed the panel, build it and rebuild the daemon:</p>
<pre><code>cd apps/web && pnpm install && pnpm run build
cargo build -p neenee-cli</code></pre>
<p>(looked for a dist at: <code>{}</code>)</p>
</main></body></html>
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_entry_escapes_windows_paths_and_asset_names() {
        let mut code = String::new();
        push_entry(
            &mut code,
            "assets/quoted\"name.js",
            "text/javascript; charset=utf-8",
            Path::new(r#"D:\a\neenee\out\web-assets\quoted"name.js"#),
        );

        assert_eq!(
            code,
            concat!(
                r#"    ("assets/quoted\"name.js", "text/javascript; charset=utf-8", include_bytes!("D:\\a\\neenee\\out\\web-assets\\quoted\"name.js")),"#,
                "\n"
            )
        );
    }
}
