[package]
name = "neenee-tui-view"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
neenee-tui = { path = "../neenee-tui" }
neenee-core = { path = "../neenee-core" }
neenee-providers = { path = "../neenee-providers" }
unicode-width = { workspace = true }
unicode-segmentation.workspace = true
similar = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
