[package]
name = "neenee-contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
inventory = { workspace = true }

[dev-dependencies]
toml = { workspace = true }

[lints]
workspace = true
