[package]
name = "neenee-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crossterm = { workspace = true }
unicode-width.workspace = true
unicode-segmentation = { workspace = true }
bitflags = "2"

[lints]
workspace = true
