[package]
name = "neenee-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
neenee-contracts = { path = "../neenee-contracts" }
neenee-persistence = { path = "../neenee-persistence" }
neenee-providers = { path = "../neenee-providers" }
neenee-skills = { path = "../neenee-skills" }
neenee-agent = { path = "../neenee-agent" }
neenee-mcp = { path = "../neenee-mcp" }
neenee-web-assets = { path = "../neenee-web-assets" }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "process", "rt", "signal", "sync", "time"] }
tokio-util = { workspace = true }
tokio-tungstenite = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
