/**
 * Wire contracts for the neenee web client.
 *
 * The payload types are GENERATED from `crates/neenee-contracts` — the serde
 * source of truth for the session-daemon WebSocket protocol per
 * `docs/reference/server-api.md` § "Contract maintenance" — by ts-rs into
 * `./generated/wire.gen.ts`. DO NOT hand-edit the generated file: it is
 * regenerated by `cargo test -p neenee-contracts` (CI fails on drift — commit
 * the regenerated file alongside any contract change).
 *
 * Hand-maintained below: only the transport envelope (`Wire`, `AttachAction`,
 * `ControlRequest`, `ControlReply`, `SessionOverview`, `WelcomePayload` —
 * defined in `crates/neenee-runtime/src/serve.rs`), the `AgentResponse` union
 * (its TUI-only variants are intentionally not modeled for the web panel), and
 * the client-side helpers.
 *
 * JSON shapes follow serde's representations exactly:
 *
 * - `Wire` envelopes: `#[serde(tag = "type")]`. `Request` / `Response` /
 *   `Monitor` payloads are flattened, so an `AgentRequest`/`AgentResponse`
 *   variant appears as a key next to `"type"`, e.g.
 *   `{"type":"Request","Chat":{"text":"…","images":[]}}`. Flattened unit
 *   variants take `null` (`{"type":"Request","Interrupt":null}`) — see the
 *   `AgentRequest` alias below for how that maps onto the generated union.
 * - `AgentResponse::Round` nests its `RoundEvent` under `"event"`, where a
 *   nested unit variant serializes as a bare string (`"event": "StreamStart"`)
 *   and newtype variants as `{"StreamDelta": "…"}`.
 * - `MonitorEvent`: `#[serde(tag = "kind", rename_all = "snake_case")]`,
 *   flattened into the envelope — its fields sit at the top level of the
 *   Monitor frame alongside `type`/`kind`.
 * - Enums without `rename_all` (Role, PermissionDecision, ReviewStatus…)
 *   keep PascalCase variant names on the wire; enums with it (SessionStatus,
 *   MonitorEvent kinds, notices…) use snake_case. The generated file mirrors
 *   the serde attributes, so casing can no longer drift.
 *
 * Wire data is authored by the daemon, so extra fields are tolerated (and
 * relied on) for forward compatibility.
 */

export * from "./generated/wire.gen.js";

import type {
  AgentRequest as AgentRequestPayload,
  CommandRecord,
  ImagePart,
  Message,
  MonitorEvent,
  PermissionDecision,
  ProviderPickerSnapshot,
  RoundEvent,
  RoundInterrupt,
  RoundSummary,
} from "./generated/wire.gen.js";

// ---------------------------------------------------------------------------
// Agent requests (client → daemon), as flattened into `Wire::Request`.
// ---------------------------------------------------------------------------

/**
 * serde flattens the externally-tagged `AgentRequest` into the `Wire::Request`
 * envelope, where a flattened unit variant appears as `{ "Variant": null }`
 * (`{"type":"Request","Interrupt":null}`) instead of the bare string ts-rs
 * models for the standalone enum. This maps the generated union onto the
 * on-the-wire envelope shapes.
 */
type FlattenedIntoEnvelope<T> = T extends string ? { [Variant in T]: null } : T;

/** `AgentRequest` as it appears flattened inside `Wire::Request`. */
export type AgentRequest = FlattenedIntoEnvelope<AgentRequestPayload>;

// ---------------------------------------------------------------------------
// Monitor plane (flattened `Wire::Monitor` frames).
// ---------------------------------------------------------------------------

/**
 * `MonitorEvent` flattened into the envelope (tag `kind`, snake_case). The
 * variant payload fields sit directly on the Monitor frame: a snapshot frame
 * reads `{"type":"Monitor","kind":"snapshot","project_root":"…",…}` and a
 * session row arrives flattened as the row object itself on `session_added` /
 * `session_updated`.
 */
export type MonitorFrame = { type: "Monitor" } & MonitorEvent;

/** The `kind` tag values of a monitor frame. */
export type MonitorEventKind = MonitorEvent["kind"];

// ---------------------------------------------------------------------------
// Round-summary helpers (mirror `RoundSummary::{active_ms, tps}` in
// crates/neenee-contracts/src/events.rs).
// ---------------------------------------------------------------------------

/** Mirrors `RoundSummary::active_ms` (wall-clock minus human-decision pause). */
export function roundActiveMs(s: RoundSummary): number {
  return Math.max(0, s.duration_ms - s.paused_ms);
}

/** Mirrors `RoundSummary::tps`; `0` when there is no usable denominator. */
export function roundTps(s: RoundSummary): number {
  const denominator = s.generation_ms > 0 ? s.generation_ms : roundActiveMs(s);
  return denominator === 0 ? 0 : (s.output_tokens * 1000) / denominator;
}

// ---------------------------------------------------------------------------
// Agent responses (daemon → client), flattened into `Wire::Response`.
// hand-maintained: `AgentResponse` carries many TUI-only variants (session
// context modal, token-usage report, OAuth connect status, /btw asides…)
// that the web panel never consumes; only the subset below is modeled.
// ---------------------------------------------------------------------------

export interface WelcomePayload {
  session_id: string;
  round_counter: number;
  messages: Message[];
  provider: string;
  model: string;
  /** Round-interrupt records (C11); absent on older daemons. */
  round_interrupts?: RoundInterrupt[];
}

export interface ConversationReplacedPayload {
  session_id: string;
  messages: Message[];
  /** Command-ledger rows (ADR-0091); absent on older daemons. */
  commands?: CommandRecord[];
  /** Round-interrupt records (C11); absent on older daemons. */
  round_interrupts?: RoundInterrupt[];
}

export type AgentResponse =
  | { Round: { session_id: string; event: RoundEvent } }
  | { ProviderKeys: [string, boolean][] }
  | { ProviderPicker: ProviderPickerSnapshot }
  | { ProviderSwitched: { provider: string; model: string } }
  // Unit variant: `{"ConversationCleared":null}` — it carries no id; the
  // fresh session's id arrives tagging the next `Round` event (handoff in
  // the store).
  | { ConversationCleared: null }
  | { ConversationReplaced: ConversationReplacedPayload }
  | { Error: string }
  | { Exit: null };

// ---------------------------------------------------------------------------
// Transport envelope (crates/neenee-runtime/src/serve.rs) — hand-maintained:
// these types live in neenee-runtime, outside the ts-rs export. They are
// small and stable.
// ---------------------------------------------------------------------------

/** `AttachAction` — snake_case (`rename_all = "snake_case"`). */
export type AttachAction =
  | "new"
  | { attach: string | null }
  | { monitor: { watch: boolean; include_idle: boolean } }
  | { control: ControlRequest };

/** `ControlRequest` — internally tagged on `verb`, snake_case. */
export type ControlRequest =
  | { verb: "create_session"; project: string; prompt?: string }
  | { verb: "send_prompt"; session_id: string; text: string }
  | { verb: "interrupt"; session_id: string }
  | {
      verb: "resolve_permission";
      session_id: string;
      request_id: string;
      decision: PermissionDecision;
    }
  | { verb: "kill_session"; session_id: string }
  | { verb: "shutdown" };

export interface ControlReply {
  ok: boolean;
  session_id?: string;
  error?: string;
}

export interface SessionOverview {
  id: string;
  overview: string;
  created_at: number;
  updated_at: number;
  message_count: number;
  active: boolean;
}

export type Wire =
  | ({ type: "Select" } & { action: AttachAction; project?: string; version?: string })
  | ({ type: "Welcome" } & WelcomePayload)
  | ({ type: "Pick" } & { sessions: SessionOverview[] })
  | ({ type: "Error" } & {
      message: string;
      /** Stable machine-readable reason (ADR-0105), e.g. `"version_mismatch"`. */
      code?: string | null;
    })
  | ({ type: "Request" } & AgentRequest)
  | ({ type: "Response" } & AgentResponse)
  | ({ type: "ControlReply" } & ControlReply)
  | MonitorFrame;
